# Generated by Django 5.2.3 on 2025-06-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="POICategory",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name="typecode",
                    ),
                ),
                (
                    "big_cn",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="大类(中文)"
                    ),
                ),
                (
                    "mid_cn",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="中类(中文)"
                    ),
                ),
                (
                    "sub_cn",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="小类(中文)"
                    ),
                ),
                (
                    "big_en",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Big Category"
                    ),
                ),
                (
                    "mid_en",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Mid  Category"
                    ),
                ),
                (
                    "sub_en",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Sub Category"
                    ),
                ),
            ],
            options={
                "verbose_name": "POI分类",
                "verbose_name_plural": "POI分类",
                "indexes": [
                    models.Index(
                        fields=["big_cn", "mid_cn", "sub_cn"],
                        name="hunter_poic_big_cn_c3dddf_idx",
                    ),
                    models.Index(
                        fields=["big_en", "mid_en", "sub_en"],
                        name="hunter_poic_big_en_bce4e3_idx",
                    ),
                ],
            },
        ),
    ]
