# Generated by Django 5.2.3 on 2025-06-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hunter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="POIKeywordAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=64, unique=True)),
                ("code", models.CharField(max_length=6)),
            ],
            options={
                "verbose_name": "POI关键词别名",
                "verbose_name_plural": "POI关键词别名",
                "indexes": [
                    models.Index(fields=["alias"], name="hunter_poik_alias_e5b872_idx")
                ],
            },
        ),
    ]
