# Generated by Django 4.2.21 on 2025-06-05 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_transport_accommodation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodation",
            name="cost_per_night",
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="total_cost",
        ),
        migrations.CreateModel(
            name="AccommodationNight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="对应哪一天的住宿费用，必须在 check_in_date 与 check_out_date 范围内"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="该晚的实际费用（可变）",
                        max_digits=10,
                    ),
                ),
                (
                    "accommodation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nights",
                        to="planner.accommodation",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("accommodation", "date")},
            },
        ),
    ]
