# Generated by Django 4.2.21 on 2025-06-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talksession",
            name="state",
            field=models.CharField(
                blank=True, help_text="当前对话状态", max_length=100
            ),
        ),
    ]
