# Generated by Django 4.2.21 on 2025-06-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talker", "0002_talksession_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talksession",
            name="state",
            field=models.JSONField(
                blank=True, default=dict, help_text="当前对话状态，包含阶段、意图等信息"
            ),
        ),
    ]
