# Generated by Django 4.2.21 on 2025-06-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talker", "0003_alter_talksession_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="talksession",
            name="user_profile",
            field=models.JSONField(
                blank=True, default=dict, help_text="用户画像，记录偏好、心情等信息"
            ),
        ),
    ]
