# Generated by Django 4.2.21 on 2025-06-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talker", "0004_talksession_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talksession",
            name="budget",
            field=models.CharField(
                blank=True, help_text="预算", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="talksession",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
