# Generated by Django 5.2.3 on 2025-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talker", "0005_alter_talksession_budget_alter_talksession_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="talksession",
            name="selected_poi",
            field=models.JSONField(
                blank=True, default=None, help_text="用户手动添加的POI", null=True
            ),
        ),
    ]
