# Generated by Django 5.2.3 on 2025-06-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talker", "0006_talksession_selected_poi"),
    ]

    operations = [
        migrations.AddField(
            model_name="talksession",
            name="timeline",
            field=models.JSONField(blank=True, default=dict, help_text="生成的时间表"),
        ),
    ]
