# Generated by Django 5.2.3 on 2025-06-30 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talker", "0007_talksession_timeline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talksession",
            name="timeline",
        ),
        migrations.CreateModel(
            name="POIItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="POI名称", max_length=200)),
                (
                    "poi_id",
                    models.CharField(
                        blank=True, help_text="高德POI ID", max_length=50, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, help_text="地址", max_length=500, null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="经纬度坐标", max_length=100, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, help_text="POI类型", max_length=100, null=True
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, help_text="电话", max_length=50, null=True
                    ),
                ),
                (
                    "distance",
                    models.CharField(
                        blank=True, help_text="距离", max_length=50, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "用户手动添加"),
                            ("reverse_search", "locations逆搜索"),
                            ("keyword_search", "关键词搜索"),
                        ],
                        help_text="POI来源",
                        max_length=20,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(default=dict, help_text="原始高德API数据"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="关联的会话",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poi_items",
                        to="talker.talksession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("session", "name", "poi_id")},
            },
        ),
    ]
