# Generated by Django 5.2.3 on 2025-06-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("talker", "0008_remove_talksession_timeline_poiitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talksession",
            name="selected_poi",
        ),
    ]
