# Generated by Django 5.2.3 on 2025-07-01 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talker", "0009_remove_talksession_selected_poi"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="poiitem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="poiitem",
            name="poi_id",
            field=models.CharField(
                default=1, help_text="高德POI ID", max_length=50, unique=True
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="poiitem",
            name="session",
        ),
        migrations.RemoveField(
            model_name="poiitem",
            name="source",
        ),
        migrations.CreateModel(
            name="POISession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "用户手动添加"),
                            ("reverse_search", "locations逆搜索"),
                            ("keyword_search", "关键词搜索"),
                        ],
                        help_text="POI来源",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poi",
                    models.ForeignKey(
                        help_text="关联的POI",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_relations",
                        to="talker.poiitem",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="关联的会话",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poi_sessions",
                        to="talker.talksession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("session", "poi")},
            },
        ),
    ]
