# Generated by Django 5.2.3 on 2025-07-06 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talker", "0010_alter_poiitem_unique_together_alter_poiitem_poi_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="POIKeywordCache",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "keyword",
                    models.CharField(
                        help_text="用户输入的关键词", max_length=200, unique=True
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=1, help_text="命中次数，便于统计热度"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "poi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_caches",
                        to="talker.poiitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
