# Generated by Django 4.2.21 on 2025-06-19 07:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("activity", "活动"),
                            ("departure", "出发"),
                            ("arrival", "到达"),
                            ("checkin", "入住"),
                            ("checkout", "退房"),
                            ("stay", "住宿"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=300)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sight", "景点"),
                            ("hotel", "酒店"),
                            ("restaurant", "餐厅"),
                            ("transport", "交通枢纽"),
                            ("custom", "自定义"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="planner.event",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sightseeing", "游览"),
                            ("dining", "餐饮"),
                            ("transport", "交通"),
                            ("rest", "休息"),
                            ("free", "自由活动"),
                            ("custom", "自定义"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
            ],
            bases=("planner.event",),
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planner.location",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="planner.trip",
            ),
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="planner.event",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("fly", "飞机"),
                            ("train", "火车"),
                            ("bus", "大巴"),
                            ("metro", "地铁"),
                            ("taxi", "出租"),
                            ("car", "自驾"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transport_destinations",
                        to="planner.location",
                    ),
                ),
            ],
            bases=("planner.event",),
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("day_index", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="planner.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["trip", "day_index"],
                "unique_together": {("trip", "date"), ("trip", "day_index")},
            },
        ),
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="planner.event",
                    ),
                ),
                (
                    "linked_accommodation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_accommodations",
                        to="planner.accommodation",
                    ),
                ),
            ],
            bases=("planner.event",),
        ),
    ]
